language: php
php:
  - "5.5"
  - "5.4"
  - "7.0"
before_script:
  - composer self-update
  - composer install --prefer-source
  
script: phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
